<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<%--This is the path if you wanted to see your generated servlet on the basis of this JSP   
E:\java-workspace\.metadata\.plugins\org.eclipse.wst.server.core\tmp1\work\Catalina\localhost\JspProject\org\apache\jsp--%>
<html>
<head>
<meta charset="ISO-8859-1">
<title>This is the Adder Jsp</title>
</head>
<body>
	<%--Below is the declaration tag which we use to declare the data members in the autogenerated servlet
or to override the methods or to define any methods in the autogenerated servlet..   --%>
	<%!private int counter = 0;

	public void jspInit() {
		System.out.println("adder.jsp is initilaise...");
		myMethod();
	}

	private void myMethod() {
		counter++;
		System.out.println(
				"this method is invoked from the init when counter is 1 and from -jspService when counter is 2:"
						+ counter);

	}%>
	<%--Below is the scriptlet tag so whatever we will write in there will go in the -jspService method   --%>
	<%
		System.out.println("We are in -jspService method..");
		myMethod();
		int num1 = Integer.parseInt(request.getParameter("num1"));
		int num2 = Integer.parseInt(request.getParameter("num2"));
	%>
	<%--Below is the expression tag this will also go in the -jspService method but it's value will get evaluated before writing it to the output stream
so if we are using this tag then we dpn't need to write the value to the outputstream by ourself this would be done by the evaluation tag..   --%>
	<h3>Sum is:</h3><%=num1 + num2%>
	<%-- Now there might be one error in the above program which is when we are trying to covert the request parameter to the integer then it might throw number format exception 
to handle that we will write the centralised error handler, below is the page directive which we are using for redirecting the request if any error occured and then we are
declaring a jsp page as error handler by using the page directive again --%>
	<%@page errorPage="errorHandler.jsp"%>
	
<%--Now below is the include action tag which we are using to include the index.html page in the output stream like the one which we
used to do with the RequestDispatcher object in the servlet and then we will check the autogenerated servlet for this --%>
<jsp:include page="index.html"></jsp:include>

<%--now below we will use the include directive and will see what would be the change in the auto generated servlet --%>
<%-- <%@include file="index.html" %> --%>
</body>
</html>